
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-frontiers-f25-11
owner: ucsb-cs156-f25
repo_name: proj-frontiers-f25-11
pull_requests: [{"author":{"id":"MDQ6VXNlcjM0MDUyMDE=","is_bot":false,"login":"Kosnax","name":"Jehmiah Pittman"},"headRefName":"jehmiah-eslintPropTypes","number":29,"title":"Enabled \"react/prop-types\" & added PropTypes to files that require them.","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-11/pull/29"},{"author":{"id":"U_kgDOCNoLqQ","is_bot":false,"login":"SagnikBiswasUCSB","name":""},"headRefName":"refactor-sign-in","number":28,"title":"refactored SignInPage and PromptSignInPage with SignInProviders compoâ€¦","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-11/pull/28"},{"author":{"id":"U_kgDOBigf6g","is_bot":false,"login":"wooblz","name":""},"headRefName":"wooblz-HelpPageLinkedforUploadCSVRoster","number":27,"title":"Added icon+link to help page for CSV formats next to 'Upload CSV Roster'","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-11/pull/27"},{"author":{"id":"U_kgDOCMFw1g","is_bot":false,"login":"AvaneeshVinothK","name":""},"headRefName":"sanitize-emails","number":26,"title":"Sanitized Emails","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-11/pull/26"}]
