
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-frontiers-f25-11
owner: ucsb-cs156-f25
repo_name: proj-frontiers-f25-11
pull_requests: [{"author":{"id":"MDQ6VXNlcjM0MDUyMDE=","is_bot":false,"login":"Kosnax","name":"Jehmiah Pittman"},"headRefName":"jehmiah-assignmentsPost","number":59,"title":"Added Assignment Controller, Post, and Tests","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-11/pull/59"},{"author":{"id":"U_kgDOCNoLqQ","is_bot":false,"login":"SagnikBiswasUCSB","name":""},"headRefName":"frontiers-csv-documentation","number":58,"title":"Frontiers csv documentation","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-11/pull/58"},{"author":{"id":"U_kgDOCNnsTg","is_bot":false,"login":"EthanChung137","name":""},"headRefName":"EthanChung137-AssignmentRepoStaffOption-Backend","number":57,"title":"Allows the option to create assignment repos to staff, students, or both","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-11/pull/57"},{"author":{"id":"MDQ6VXNlcjM0MDUyMDE=","is_bot":false,"login":"Kosnax","name":"Jehmiah Pittman"},"headRefName":"jehmiah-EslintDisplayNames","number":53,"title":"Enabled \"react/display-name\" & added Display Names to files that require them","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-11/pull/53"}]
