
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-frontiers-f25-11
owner: ucsb-cs156-f25
repo_name: proj-frontiers-f25-11
pull_requests: [{"author":{"id":"U_kgDOCMFw1g","is_bot":false,"login":"AvaneeshVinothK","name":""},"headRefName":"sanitize-emails","number":26,"title":"Sanitized Emails","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-11/pull/26"},{"author":{"id":"U_kgDOCNnsTg","is_bot":false,"login":"EthanChung137","name":""},"headRefName":"EthanChung137-CourseStaffController-OrgRemovalOption","number":24,"title":"Added option to remove courseStaff from git org in delete endpoint","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-11/pull/24"}]
